### PR TITLE
support bool type

### PR DESCRIPTION
**Pull request by qihangnet**

### CODE REVIEW

**Comment by Vidarls** [comment]
Is this the bit type you are referring to: https://dev.mysql.com/doc/refman/5.0/en/bit-type.html?

**Comment by rippo** [comment]
Isn't  BOOL or BOOLEAN a synonym for TINYINT(1) ?

**Comment by Vidarls** [comment]
@rippo That is what I use (tinyint(1)), this `bit` type seems to support binary strings `10011` in some sort of native way. To me it looks like it could map to a `long`(int64) as it seems to support u to 64 bits . Not sure it maps in any way to a `bool`. But then again, I've never actually used this bit type. Maybe @qihangnet can shed some light here :)

**Comment by qihangnet** [comment]
@Vidarls For Boolean types of data, I personally think bit type should be used instead of tinyint。This practice, should be universal and not only for mysql。

Some reference links:

- https://github.com/markrendle/Simple.Data/blob/master/Simple.Data.SqlServer/SqlTypeResolver.cs
- https://github.com/markrendle/Simple.Data/blob/master/Simple.Data.SqlServer/SqlDbTypeEx.cs
- https://github.com/NotMyself/Simple.Data.Sqlite/blob/master/src/Simple.Data.Sqlite/SqliteTypeResolver.cs
- https://github.com/markrendle/Simple.Data/blob/master/Simple.Data.SqlCe40/SqlTypeResolver.cs
- https://github.com/richardhopton/Simple.Data.SqlAnywhere/blob/master/Simple.Data.SqlAnywhere/SqlAnywhereTypeResolver.cs
- http://stackoverflow.com/questions/289727/
- http://en.wikipedia.org/wiki/Bit
- http://en.wikipedia.org/wiki/Integer_(computer_science)

**Comment by qihangnet** [comment]
and another link:
https://github.com/markrendle/Simple.Data.VistaDB/blob/master/Simple.Data.VistaDB/VistaDBTypeResolver.cs

**Comment by Vidarls** [comment]
Referring to other providers makes little sense, as datatypes are not the sign cross DB.

I can see that bit _used to be_ an alias for `tinyint(1)` but after 5.0.3 it started behaving differently.

As far as I understand the docs: https://dev.mysql.com/doc/refman/5.0/en/bit-type.html a bit field can contain up to __64__ bits. 64 bits does not translate to a boolean.

See also: http://stackoverflow.com/questions/290223/

The question then is what _can be_ a good representation for a bit field? 

A bit field is just raw bits, no indication of msb or lsb. This means we can not reliably present as int or uint.

Maybe a boolean array is the best representation? any thoughts? I'm a bit stuck

**Comment by Vidarls** [comment]
Closing for now. 
Please reopen or raise a new one if any new information should become available.

**Comment by Vidarls** [comment]
#34 is now an initial support of the binary data format

**Pull request closed without merging**
